# Generated by Django 4.1.13 on 2024-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('read_time', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('updated_date', models.DateTimeField(verbose_name='updated date')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
            ],
            options={
                'db_table': 'django_news',
            },
        ),
    ]
