# Generated by Django 4.1.13 on 2024-01-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_curate', '0002_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(),
        ),
    ]
