# Generated by Django 4.1.13 on 2024-01-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_curate', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
