# Generated by Django 4.1.13 on 2024-01-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_curate', '0005_remove_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
